### ISSUE TITLE
Changes in ffi-inline-0.0.4.gem are not merged to github

### ISSUE THREAD

**Issue by larskanis** [meh/ruby-ffi-inline#4]
Hi @meh,

the latest ffi-inline gem has changed the file naming from 'ffi-inliner' to 'ffi-inline', but this change is missing in your github repo. Could you update it?

Regards,
Lars

**Comment by meh** [comment]
What do you mean?

**Comment by larskanis** [comment]
ffi-inline-0.0.3 and this repo have 'lib/ffi/inliner.rb' and v0.0.4 on rubygems.org has 'lib/ffi/inline.rb'. So there seems to be an missung push to this repo with the changes of v0.0.4.

**Comment by meh** [comment]
Oh snap, true, rebasing/pushing and I'll push a new gem too.

**Comment by larskanis** [comment]
Great, thank you!
